/* XENSIV BGT60TRXX register configurator, SDK version3.6.4+4b4a62456 */

#ifndef XENSIV_BGT60TRXX_CONF_H
#define XENSIV_BGT60TRXX_CONF_H

#define XENSIV_BGT60TRXX_CONF_DEVICE (XENSIV_DEVICE_BGT60TR13C)
/* Long-range chirp: center ~61.25 GHz, span ~1.4 GHz, both endpoints inside
 * the BGT60TR13C legal band (58.0-63.5 GHz). Gives ~0.107 m range resolution
 * (was ~0.075 m at the 2.0 GHz BW), so the 64-bin range FFT spans ~6.85 m.
 * Generated by bgt60-configurator-cli from config_1400mhz.json (lower
 * 60.55 GHz / upper 61.95 GHz, 128 samples, 32 chirps, 2 MHz sample rate)
 * -- do not hand-edit; regenerate via the CLI. */
#define XENSIV_BGT60TRXX_CONF_START_FREQ_HZ (60550001000)
#define XENSIV_BGT60TRXX_CONF_END_FREQ_HZ (61950001000)
#define XENSIV_BGT60TRXX_CONF_NUM_SAMPLES_PER_CHIRP (128)
#define XENSIV_BGT60TRXX_CONF_NUM_CHIRPS_PER_FRAME (32)
#define XENSIV_BGT60TRXX_CONF_NUM_RX_ANTENNAS (2)
#define XENSIV_BGT60TRXX_CONF_NUM_TX_ANTENNAS (1)
#define XENSIV_BGT60TRXX_CONF_SAMPLE_RATE (2000000)
#define XENSIV_BGT60TRXX_CONF_CHIRP_REPETITION_TIME_S (0.000499888)
#define XENSIV_BGT60TRXX_CONF_FRAME_REPETITION_TIME_S (0.150149)
#define XENSIV_BGT60TRXX_CONF_NUM_REGS (38)

#if defined(XENSIV_BGT60TRXX_CONF_IMPL)
/* Only the two PLL1 frequency-ramp registers changed vs the 2.0 GHz config;
 * every ADC / sample-rate / timing / RX-enable register is identical, so
 * chirp duration and sample rate are preserved:
 *   addr 0x30 PLL1_0 (FSU, ramp start): 0x61e0da96 -> 0x61e8c5d0
 *   addr 0x31 PLL1_1 (RSU, freq step) : 0x63000262 -> 0x630001ab */
const uint32_t register_list[] = {
    0x11e8270UL,
    0x30a0210UL,
    0x9e967fdUL,
    0xb0805b4UL,
    0xd1027ffUL,
    0xf010700UL,
    0x11000000UL,
    0x13000000UL,
    0x15000000UL,
    0x17000be0UL,
    0x19000000UL,
    0x1b000000UL,
    0x1d000000UL,
    0x1f000b60UL,
    0x2113cc51UL,
    0x236ff41fUL,
    0x25006f7bUL,
    0x2d000490UL,
    0x3b000480UL,
    0x49000480UL,
    0x57000480UL,
    0x5911be0eUL,
    0x5b6d1c0aUL,
    0x5d01f000UL,
    0x5f787e1eUL,
    0x61e8c5d0UL,  /* PLL1_0 FSU: start 60.55 GHz (was 0x61e0da96) */
    0x630001abUL,  /* PLL1_1 RSU: ~1.4 GHz bandwidth (was 0x63000262) */
    0x650002b2UL,
    0x67000080UL,
    0x69000000UL,
    0x6b000000UL,
    0x6d000000UL,
    0x6f275b10UL,
    0x7f000100UL,
    0x8f000100UL,
    0x9f000100UL,
    0xad000000UL,
    0xb7000000UL,
};
#endif /* XENSIV_BGT60TRXX_CONF_IMPL */

#endif /* XENSIV_BGT60TRXX_CONF_H */
